collections_dir: collections    
collections:
  introduction:
    title: introduction
    position: 1  
  reference:
    title: reference
    position: 2    
  transcoding:
    title: transcoding
    position: 3       